import zipfile
import os

# Pfad zur ZIP-Datei und Zielordner
zip_file_path = r'C:\Users\luklu\OneDrive\Dokumente\SSBSV55\V55 Brawl.zip'
destination_folder = r'C:\Users\luklu\OneDrive\Dokumente\SSBSV55\V55_Brawl_Unpacked'

# Sicherstellen, dass der Zielordner existiert
if not os.path.exists(destination_folder):
    os.makedirs(destination_folder)

# Entpacken der ZIP-Datei
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(destination_folder)

print(f"ZIP-Datei erfolgreich entpackt in {destination_folder}")
