name: Unzip file

on:
  push:
    paths:
      - '**/V55 Brawl.tip'  # Dies löst den Workflow aus, wenn eine Datei namens V55 Brawl.tip hochgeladen wird.

jobs:
  unzip:
    runs-on: ubuntu-latest  # Der Job läuft auf einem Ubuntu-Linux-Server.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkt das Repository aus.

      - name: Rename and Unzip the file
        run: |
          # Wenn es sich wirklich um eine ZIP-Datei handelt, aber die Endung falsch ist
          mv 'V55 Brawl.tip' 'V55_Brawl.zip'  # Umbenennen der Datei in .zip
          unzip 'V55_Brawl.zip' -d unzipped/  # Entpacken der ZIP-Datei in den Zielordner 'unzipped'.
