name: Unzip file

on:
  push:
    paths:
      - '**/V55 Brawl.tip'  # Diese Regel löst den Workflow aus, wenn eine Datei namens V55 Brawl.tip hochgeladen wird.

jobs:
  unzip:
    runs-on: ubuntu-latest  # Der Job läuft auf einem Ubuntu-Linux-Server.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkt das Repository aus, damit der Code verfügbar ist.

      - name: Install unzip
        run: sudo apt-get install unzip  # Installiert das Unzip-Tool, falls erforderlich.

      - name: Rename and Unzip the file
        run: |
          mv 'V55 Brawl.tip' 'V55_Brawl.zip'  # Rennt die Datei um, falls es eine ZIP-Datei ist.
          unzip 'V55_Brawl.zip' -d unzipped/  # Entpackt die ZIP-Datei in den Zielordner 'unzipped'.
